### ISSUE TITLE
Problem for change  the Baudrate

### ISSUE THREAD

**Issue by rosvig** [danjperron/PicMultiPurpose#2]
Hi Daniel, i am try change the baudrate value (57600 to 9600) i changed baudrate on file IOCONFIG.h but is not working :(
Did you ever try to change this value ? if is yes, please Would you tell me how did you do it?

**Comment by danjperron** [comment]
ok I used a cpp preprocessor on my code to see if I got the defines set properly and I got this in my IOConfig.h 
#define BAUD 9600
#define _XTAL_FREQ 32000000

```
daniel@linuxserver:~/PicMultiPurpose$ cpp main.c
 BRGH =0;
 BRG16 = 1;
 SYNC =0;
 SPBRGL = 207;
 SPBRGH =0;
# 1335 "main.c"
```

And if I look into this webpage  [http://www.nicksoft.info/el/calc](http://www.nicksoft.info/el/calc/?ac=spbrg&submitted=1&mcu=PIC12F1840&Fosc=32&FoscMul=1000000&FoscAutoSelector=0&MaxBaudRateError=1)

Then it should work!  I will compile and burn a pic  wednesday night to confirm this.

**Comment by danjperron** [comment]
Ok I maybe found why it's not working on 9600.

I did some change and the default timeout delay is always 200 us to switch off the RS-485 TX Enable line.    the time out should be between 1 and 1.5 BAUD then on 9600 BAUD it should be around 1200us

To fix it  change the delay in main.c (line 1394)

__delay_us(1200);

I will revisit that issue in my code

**Comment by rosvig** [comment]
Hi, i did the change of value of the delay that you told me and now is working with a 9600 baudrate.  👍 Thank you 😄 

Daniel excuse me but i want to do a correction in your schematic, because when i did the connection i verified that RO and DI of LTC485N are connected to PIC12F1840 inverted, when i changed the connection the communication started work.

Here i send the connection correctly:
![schematic1](https://user-images.githubusercontent.com/29924239/28616408-f1aa83f6-71fc-11e7-8a89-89004db80903.jpg)

**Comment by danjperron** [comment]
Thank you for the schematic correction. I will update my github tonight ;-)
